perl/perl.bzl
- reformat bzl file
- remove deprecated API
- use modern providers
- avoid string/depset iteration
Tested:
`bazel20 test //... --all_incompatible_changes --incompatible_disable_deprecated_attr_params=false --incompatible_new_actions_api=false`
Remaining issues are inside Bazel, as far as I know.
=> Fix for Bazel incompatible changes

perl/perl.bzl
Perl's construct for the traditional 'continue' statement in other
languages is 'next'.
=> replace continue with next

perl/perl.bzl
With the command line flag --nobuild_runfile_links, the tool wrapper
for perl cannot find the runfiles anymore. It searches outside the
sandbox due to the resolution of the symlinks. But with the flag
applied, the runfiles tree is not created outside the sandbox.
With this change, the wrapper scripts also works if the runfiles tree
is omitted.
=> perl_rules: Fix runfiles lookup in sandbox

perl/perl.bzl
See https://github.com/bazelbuild/bazel/issues/10860.
=> Migrate to the modern linker input API.

perl/binary_wrapper.tpl
This allows using "perl_binary" in "genrule" targets.
Signed-off-by: Piotr Sikora <piotrsikora@google.com>
=> Fix path to the executable in "perl_binary".

perl/perl.bzl
Signed-off-by: Piotr Sikora <piotrsikora@google.com>
=> Add support for "linkopts" in "perl_xs" targets.

README.md
With WORKSPACE and BUILD example.
The "git_repository" approach.
Taking inspiration from rules_python: https://github.com/bazelbuild/rules_python/blob/main/README.md
=> Add getting started section to README.md

perl/perl.bzl
I tried to follow the advice from the [Bazel docs](https://docs.bazel.build/versions/4.2.1/skylark/rules.html#runfiles-features-to-avoid) and read only `default_runfiles` of dependencies and set only `files` in `DefaultInfo` and this seems to fix the bug for me.
Fixes #28
=> Fix perl_binary target not working as a data dependency

perl/private/BUILD.dist.bazel.tpl, perl/repo.bzl
When using the perl toolchain and specifying a platform on the bazel
command line (e.g. --platforms=:android), the command would fail as
bazel required a perl toolchain that is "target compatible" with the
":android" platform. Unlike a C++ toolchain, the perl toolchain is
compatible with any target platform therefore no `target_compatible_with` should be specified
=> fix issue where rules_perl could not used for cross compilation

README.md, perl/deps.bzl, perl/repo.bzl, perl/toolchain.bzl
This toolchain can be used to build OpenSSL for Windows under Bazel.
=> Provide Strawberry Perl toolchain for Windows (#30)

BUILD, WORKSPACE, perl/deps.bzl, perl/private/BUILD.dist.bazel.tpl, perl/repo.bzl
Previously, the darwin, linux and windows variants of perl would be downloaded even if only one of them were required.
Now, only the required toolchains are downloaded.
=> Fetch only required perl

.bazelci/presubmit.yml, WORKSPACE, examples/cpan_remote/BUILD, examples/cpan_remote/fcgi.BUILD, examples/cpan_remote/fcgi_import_test.t, perl/perl.bzl
Signed-off-by: Piotr Sikora <piotrsikora@google.com>
=> Allow C/C++ sources in "perl_xs" target.

WORKSPACE, examples/genhtml/BUILD, examples/genhtml/coverage.dat, examples/genhtml/genhtml.BUILD, examples/genhtml/genhtml_test.t, perl/perl.bzl
Perl source files without a file extension are relatively common ([genhtml](https://github.com/linux-test-project/lcov/blob/master/bin/genhtml) is an example).
=> Allow Perl source with no file extension

BUILD, perl/deps.bzl, perl/toolchain.bzl
The relocatable perl binary distribution distributes "fat" darwin
binaries that are capable of working on both architectures, so adjust
the build rules so that it works.
Now on an M1 mac you can do this:
cd examples/hello_world
bazel run :hello_world
=> Adjust rules_perl to work with darwin amd64 and arm architectures

BUILD
See https://github.com/bazel-contrib/rules-template/pull/9.
I hit this while cross-compiling C++ code that transiently required perl for building.
=> fix: remove target_compatible_with

BUILD
I see that this was missed in PR #44
I haven't encountered any errors related to it, but it seems like removing it from osx would also be the correct move.
=> Remove target_compatible_with on osx

BUILD, WORKSPACE, perl/deps.bzl, platforms.bzl
I'm new to rules_perl (wanted to try it for genhtml), but couldn't use on my M1 mac.  Given #52 was outstanding issue, went ahead and added this.
Newest release of [relocatable-perl 5.36.0.1]() has a much more consistent asset naming convention, so I went ahead and simplified the toolchain naming / setup.
=> Upgrade to relocatable-perl 5.36.0.1

MODULE.bazel, perl/deps.bzl, perl/extensions.bzl
Adds files to make it possible to use ``rules_perl`` using bzlmod.
This can be used in a ``MODULES.bazel`` using a snippet like:
```
bazel_dep(name = "rules_python", version = "0.1.0")
archive_override(
module_name = "rules_perl",
urls = [
"https://github.com/bazelbuild/rules_perl/archive/76bc70ef16b4bab2d6c9cd5ea387405e6b3bee6a.tar.gz",
],
strip_prefix = "rules_perl-76bc70ef16b4bab2d6c9cd5ea387405e6b3bee6a",
integrity = "sha256-uHDm8XnLUKTMzaXykUAth63MrG3xhG77FhtYcANCrI0=",
)
```
Note: The ``archive_override`` can be removed if you also start publishing releases to registry.bazel.build.
=> Enable bzlmod

MODULE.bazel
`rules_perl` requires the `rules_cc` repository to be present: https://github.com/bazelbuild/rules_perl/blob/022b8daf2bb4836ac7a50e4a1d8ea056a3e1e403/perl/perl.bzl#L19
While this isn't an issue when running the examples for this repo (i.e. `bazel build --enable_bzlmod //examples/hello_world:hello_world` works fine — rules_cc appears to be implicitly added to the repo mapping for the current root module's repo), when depending on `rules_perl` from another module this becomes an issue.
Even if the dependent pulls in the `rules_cc` module, `rules_cc` will not be visible in `rules_perl`'s mapping unless `rules_perl` also declares a dependency on it.
=> Add a dependency for `rules_cc` to `MODULE.bazel`

perl/toolchain.bzl
When using rules_perl with nmake on windows, the exported path to PERL has `/` instead of `\`. This causes nmake targets to break.
For example when nmake need to execute a target that needs to run:
```
C:\users\jsun\_bazel_jsun\2pzzqzw2\execroot\splcore\external/perl_windows_x86_64/perl/bin/perl.exe util/mkdir-p.pl
```
It returns the error
```
'C:\users\jsun\_bazel_jsun\2pzzqzw2\execroot\splcore\external' is not recognized as an internal or external command,
operable program or batch file.
NMAKE : fatal error U1077: 'C:\users\jsun\_bazel_jsun\2pzzqzw2\execroot\splcore\external' : return code '0x1'
Stop.
```
This PR fixes this by checking for the appropriate windows platform constraint and replacing the path separator as needed. The method is documented …
=> Fix windows path incompatibility

BUILD, MODULE.bazel, perl/BUILD, perl/deps.bzl, perl/perl.bzl, perl/toolchain.bzl
It's more common for `bazelbuild` rules repos to have targets in the rules package. This change updates `rules_perl` to meet that expectation so developers introducing the rules to their repo have a slightly easier time.
Aliases have been added to avoid a backwards incompatible change.
=> Moved targets into `//perl` package and aliased original locations

perl/perl.bzl
The reason it did not work was that the code assumed that the execpath of any artifact can be passed to `ctx.actions.declare_file()`, but that's not the case for artifacts not in the main repository when sibling repository layout is in effect: their paths start with `../` which would make them ascend above the package directory.
This also triggered a bug in Bazel
(https://github.com/bazelbuild/bazel/issues/22362), but even if that bug didn't exist, this would still not work.
Serendipitously, the principled fix for
`--experimental_sibling_repository_layout` is also a workaround for the above bug. It adds two path segments to the package-relative path of the .o file, akin to how c++ rules work.
=> Makes rules_perl work with `--experimental_sibling_repository_layout`.

README.md, examples/cpan/BUILD, examples/cpan_remote/BUILD, examples/cpan_remote/fcgi.BUILD, examples/external_module/BUILD, perl/binary_wrapper.tpl, perl/perl.bzl
The current advice for loading perl_libraries is to manually add a `PERL5LIB` env on perl_binary.
This only really works for perl_library dependencies in the same workspace and for external dependencies in WORKSPACE mode. In Bzlmod paths like `../fcgi/lib` can't be hard-coded (at least not when the repo isn't always _main but is a library itself).
This PR automates setting the PERL5LIB by means of a new `includes` attr on the perl_library rule.
This seems to work well in my (very limited) test environment.
(Note: I needed to comment out HAVE_DEV_PTMX to get the perl_xs to compile on my machine 🤷)
=> Add `includes` attr to automate `$PERL5LIB`

WORKSPACE, WORKSPACE.bzlmod, perl/deps.bzl
`@fcgi` and `@genhtml` weren't pulled in correctly for testing under Bzlmod
=> Extract dev deps to function and add in Bzlmod via WORKSPACE.bzlmod

perl/binary_wrapper.tpl, test/data_dep/BUILD
I had the issue that the binary wrapper fails when it is a data dependency of some other program which is run under `bazel run` (it does work under `bazel test`!)
The issue is that during bazel run RUNFILES_DIR may not be set and the MANIFEST file may not exist at ../.. even if you did not cd somewhere else.
The correct thing to do for the wrapper in this case is to accept the interpreter short path and main short path as-is from the starlark side. We can just set PATH_PREFIX=./ for the same effect.
I added a test that is red without the binary_wrapper change and becomes green when the change is applied. The trick here is to use `env -i` to remove the test envs from the sh_test so it behaves more like a bazel run and not bazel test.
Note that I don't think the binary_wrapper should …
=> Set `PATH_PREFIX=./` instead of failing to bazel run a program with a perl_binary data dep

perl/perl.bzl
https://github.com/bazelbuild/bazel/issues/23574 is flipped for Bazel 8 but [`ctx.label.workspace_root`](https://bazel.build/rules/lib/builtins/Label.html#workspace_root) still includes an `external/` prefix. Replacing that with `../` makes rules_perl (and rules_cpan) work with Bazel 8 (https://github.com/bazelbuild/bazel-central-registry/issues/3056).
=> Support `--nolegacy_external_runfiles`

platforms.bzl
[Current and the latest version of rules_perl](https://github.com/bazelbuild/rules_perl/blob/main/platforms.bzl) are using Perl version 5.36.0.
This version is affected by CVE-2023-47100: from (including) 5.30.0 up to (excluding) 5.38.2
This PR upgrades the dependency to use a version of Perl without CVE-2023-47100 vulnerability on Linux and Mac. I do not have the ability to validate windows changes so did not upgrade the perl version on windows. I did test that genhtml was working correctly on linux and mac.
=> upgrade version of perl to evade CVE-2023-47100

platforms.bzl
This PR updates the perl version for Linux and Mac, because RHEL9 does not ship `lincrypt.so.1` which prevents perl from running
=> Update to 5.40.1.0
